add isubmit
hemisemidemipresent/cyberquincy pull request #198
Opened 2022-08-26 00:54 UTC by Tree69420

im pretty sure i fixed it

2022-08-26 15:57 UTC, ToasterSticks requested changes
Why is VTSG being added again?

2022-08-26 15:59 UTC, Tree69420 commented
bruh it adds that?

2022-08-26 16:32 UTC, Tree69420 commented
ok vtsg is gone

2022-09-10 01:36 UTC, Tree69420 commented
hi hemi merge this

2022-09-10 03:42 UTC, merged